CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;

CREATE TABLE IF NOT EXISTS public.usuarios (
  id_usuario integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  apellido character varying(100) NOT NULL,
  nombre character varying(100) NOT NULL,
  nombre_usuario character varying(45) NOT NULL UNIQUE,
  contrasenia character varying(100) NOT NULL,
  activo smallint NOT NULL
);

CREATE TABLE IF NOT EXISTS public.cursos_estados (
  id_curso_estado smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descripcion character varying(45) NOT NULL,
  es_activo smallint NOT NULL
);

CREATE TABLE IF NOT EXISTS public.inscripciones_estados (
  id_inscripcion_estado smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descripcion character varying(45) NOT NULL,
  es_activo smallint NOT NULL
);

CREATE TABLE IF NOT EXISTS public.estudiantes (
  id_estudiante integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  documento character varying(20) NOT NULL UNIQUE,
  apellido character varying(100) NOT NULL,
  nombres character varying(100) NOT NULL,
  email character varying(255) NOT NULL UNIQUE,
  fecha_nacimiento date NOT NULL,
  activo smallint NOT NULL,
  id_usuario_modificacion integer NOT NULL REFERENCES public.usuarios(id_usuario),
  fecha_hora_modificacion timestamp without time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS public.cursos (
  id_curso integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre character varying(45) NOT NULL,
  descripcion text NOT NULL,
  fecha_inicio date NOT NULL,
  cantidad_horas integer NOT NULL,
  inscriptos_max smallint NOT NULL,
  id_curso_estado smallint NOT NULL REFERENCES public.cursos_estados(id_curso_estado),
  id_usuario_modificacion integer NOT NULL REFERENCES public.usuarios(id_usuario),
  fecha_hora_modificacion timestamp without time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS public.inscripciones (
  id_inscripcion integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_curso integer NOT NULL REFERENCES public.cursos(id_curso),
  id_estudiante integer NOT NULL REFERENCES public.estudiantes(id_estudiante),
  fecha_hora_inscripcion timestamp without time zone NOT NULL,
  id_inscripcion_estado smallint NOT NULL REFERENCES public.inscripciones_estados(id_inscripcion_estado),
  id_usuario_modificacion integer NOT NULL REFERENCES public.usuarios(id_usuario),
  fecha_hora_modificacion timestamp without time zone NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_cursos_estado ON public.cursos(id_curso_estado);
CREATE INDEX IF NOT EXISTS idx_cursos_usuario ON public.cursos(id_usuario_modificacion);
CREATE INDEX IF NOT EXISTS idx_estudiantes_usuario ON public.estudiantes(id_usuario_modificacion);
CREATE INDEX IF NOT EXISTS idx_inscripciones_curso ON public.inscripciones(id_curso);
CREATE INDEX IF NOT EXISTS idx_inscripciones_estado ON public.inscripciones(id_inscripcion_estado);
CREATE INDEX IF NOT EXISTS idx_inscripciones_estud ON public.inscripciones(id_estudiante);
CREATE INDEX IF NOT EXISTS idx_inscripciones_usuario ON public.inscripciones(id_usuario_modificacion);

INSERT INTO public.usuarios (id_usuario, apellido, nombre, nombre_usuario, contrasenia, activo) VALUES
  (1, 'BIANCHI', 'LUCIANA', 'lbianchi', '7628ea83cc52ffb1fe875675326a97cd7ca71f1e3da8fba7301db782ba606b45', 1),
  (2, 'FERNANDEZ', 'LORENZO', 'lfernandez', '7845c21dcefd691b0d70063da7c68bcb8a25ac29d0a1dee5fdb8800870f9afae', 1),
  (3, 'RINCON', 'MATEO', 'mrincon', 'ade69c2785589f42b82dd048c0f09dcd485c74ada573d334731aa99d7b4627fd', 1),
  (4, 'DECHAT', 'GUILIANA', 'gdechat', 'e0b0e46fd41b7af118b2a65046c207d5b3b8a1c03bc2f9472e7e76efe7a6ed0f', 1),
  (5, 'NOVELLO', 'IGNACIO', 'inovello', 'a1d19e9e32012744ce6864d933c25417bd8faf6b320bcf3ebe91606f1f7f36bc', 1)
ON CONFLICT (id_usuario) DO NOTHING;

INSERT INTO public.cursos_estados (id_curso_estado, descripcion, es_activo) VALUES
  (1, 'BORRADOR', 1),
  (2, 'INSCRIPCION ABIERTA', 1),
  (3, 'INSCRIPCION CERRADA', 1),
  (4, 'ELIMINADO', 0)
ON CONFLICT (id_curso_estado) DO NOTHING;

INSERT INTO public.inscripciones_estados (id_inscripcion_estado, descripcion, es_activo) VALUES
  (1, 'CONFIRMADA', 1),
  (2, 'CANCELADA', 0)
ON CONFLICT (id_inscripcion_estado) DO NOTHING;

INSERT INTO public.estudiantes (id_estudiante, documento, apellido, nombres, email, fecha_nacimiento, activo, id_usuario_modificacion, fecha_hora_modificacion) VALUES
  (6, '35211111', 'GARCIA', 'MATEO EMILIO', 'mateogarcia@gmail.com', '2000-02-15', 1, 1, '2023-03-06 17:30:00'),
  (7, '28922222', 'TORRES', 'SANTIAGO JULIAN', 'santiagotorres@gmail.com', '1994-05-10', 1, 1, '2023-03-07 18:15:00'),
  (8, '38133333', 'GOMEZ', 'LUISA LUCIANA', 'luisalopez@gmail.com', '2002-01-05', 1, 1, '2023-03-08 19:00:00'),
  (9, '31944444', 'RIVAS', 'GABRIEL EDUARDO', 'gabrielrivas@gmail.com', '1997-09-25', 1, 1, '2023-03-09 20:45:00'),
  (10, '34855555', 'MARTINEZ', 'VALENTINA SOFIA', 'valentinamartinez@gmail.com', '2000-08-15', 1, 1, '2023-03-10 22:30:00')
ON CONFLICT (id_estudiante) DO NOTHING;

INSERT INTO public.cursos (id_curso, nombre, descripcion, fecha_inicio, cantidad_horas, inscriptos_max, id_curso_estado, id_usuario_modificacion, fecha_hora_modificacion) VALUES
  (1, 'Programacion Web con React', 'Desarrollo de aplicaciones web modernas utilizando JavaScript, React y consumo de APIs REST.', '2026-04-20', 60, 30, 1, 1, '2026-04-12 09:00:00'),
  (2, 'Introduccion a IA', 'Conceptos basicos de inteligencia artificial, machine learning y aplicaciones practicas con Python.', '2026-05-05', 50, 25, 1, 1, '2026-04-12 09:10:00'),
  (3, 'Seguridad Informatica', 'Fundamentos de ciberseguridad, analisis de vulnerabilidades y tecnicas de hacking etico.', '2026-05-10', 70, 20, 1, 1, '2026-04-12 09:20:00'),
  (4, 'Bases de Datos SQL y NoSQL', 'Diseno, consulta y optimizacion de bases de datos relacionales y no relacionales.', '2026-04-25', 55, 35, 1, 1, '2026-04-12 09:30:00'),
  (5, 'Backend con Node.js', 'Construccion de APIs robustas utilizando Node.js, NestJS y bases de datos SQL.', '2026-05-15', 65, 30, 1, 1, '2026-04-12 09:40:00')
ON CONFLICT (id_curso) DO NOTHING;

SELECT setval(pg_get_serial_sequence('public.usuarios', 'id_usuario'), COALESCE((SELECT MAX(id_usuario) FROM public.usuarios), 1), true);
SELECT setval(pg_get_serial_sequence('public.cursos_estados', 'id_curso_estado'), COALESCE((SELECT MAX(id_curso_estado) FROM public.cursos_estados), 1), true);
SELECT setval(pg_get_serial_sequence('public.inscripciones_estados', 'id_inscripcion_estado'), COALESCE((SELECT MAX(id_inscripcion_estado) FROM public.inscripciones_estados), 1), true);
SELECT setval(pg_get_serial_sequence('public.estudiantes', 'id_estudiante'), COALESCE((SELECT MAX(id_estudiante) FROM public.estudiantes), 1), true);
SELECT setval(pg_get_serial_sequence('public.cursos', 'id_curso'), COALESCE((SELECT MAX(id_curso) FROM public.cursos), 1), true);
SELECT setval(pg_get_serial_sequence('public.inscripciones', 'id_inscripcion'), COALESCE((SELECT MAX(id_inscripcion) FROM public.inscripciones), 1), true);
